name: Build Phoenix OS Live USB

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build-live-iso:
    runs-on: ubuntu-24.04

    steps:
      - name: Download Phoenix OS source
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            live-build \
            debootstrap \
            squashfs-tools \
            xorriso \
            grub-pc-bin \
            grub-efi-amd64-bin \
            mtools \
            dosfstools \
            isolinux \
            syslinux-common \
            syslinux-utils

      - name: Check isohybrid
        run: |
          echo "Checking for isohybrid..."

          command -v isohybrid

          isohybrid --version || true

      - name: Make build script executable
        run: |
          chmod +x scripts/build.sh

      - name: Build Phoenix OS Live USB ISO
        run: |
          sudo ./scripts/build.sh

      - name: Check finished ISO
        run: |
          echo "Checking the output folder..."

          ls -lah output/

          if [ ! -f output/Phoenix-OS-Live-amd64.iso ]; then
            echo "ERROR: Phoenix OS ISO was not found."
            exit 1
          fi

          echo "Phoenix OS ISO found!"

          ls -lh output/Phoenix-OS-Live-amd64.iso

      - name: Upload Phoenix OS Live USB
        uses: actions/upload-artifact@v4
        with:
          name: Phoenix-OS-Live-USB
          path: output/Phoenix-OS-Live-amd64.iso
          if-no-files-found: error
          retention-days: 30
